name: arsitektur_app
description: "An app to display architectural materials and AR models."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For simple and stable AR viewing.
  model_viewer_plus: ^1.7.0


  # For creating beautiful icons and layouts.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/materi/
    - assets/3d/
    - assets/icon/
