name: arsitektur_app
description: "An app to display architectural materials and AR models."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  model_viewer_plus: ^1.7.0
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  url_launcher: ^6.2.5
  syncfusion_flutter_pdfviewer: ^28.2.3
  
  # ADDED: To save models to local storage
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/materi/
    - assets/3d/
    - assets/icon/